# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name             : Rafael Mello Campanari
version          : 0.5
title            : automaite.com
email            : rafael@automaite.com
description      : Automaite's website
url              : "https://automaite.com"
twitter_username :
github_username  : melloc01
year             : 2017
markdown         : kramdown
